### PR TITLE
docs: update docs to add new api integration

### PR DESCRIPTION
**Pull request by sabinbaniya**

### CODE REVIEW

**Review by crazydevlegend — CHANGES_REQUESTED** [review]
@sabinbaniya I still see OpenAI api key related documents here...
they're no longer needed here and instead you could use BitAPAI key

**Comment by sabinbaniya** [comment]
> @sabinbaniya I still see OpenAI api key related documents here... they're no longer needed here and instead you could use BitAPAI key

Yeah, sure. I was unsure about that, Will remove them now

**Comment by crazydevlegend** [comment]
- screenshot should be replaced
- change `Next Up` section
    * Langchain wrapper
- remove `Deploy using Docker` section
- update `Configuration` section
- update `Contact` section
     `If you have any questions, feel free to reach out to [@crazydevlegend](https://github.com/crazydevlegend)`

@sabinbaniya

**Review by crazydevlegend — CHANGES_REQUESTED** [review]
so far, looks nice, 

image
plz fix this issue (text color blinds into the background)

**Pull request merged**
