### PR TITLE
feat: remove openai integration

### PR DESCRIPTION
**Pull request by sabinbaniya**

### CODE REVIEW

**Comment by crazydevlegend** [comment]
@sabinbaniya can you plz share screenshot?

**Comment by sabinbaniya** [comment]
> @sabinbaniya can you plz share screenshot?

Okay

**Comment by sabinbaniya** [comment]
> @sabinbaniya can you plz share screenshot?

New conversation:
image

Continued conversation:
Screenshot 2023-06-28 083533

**Comment by crazydevlegend** [comment]
image
I still see openai, chatgpt here...
Please check all pages and confirm all are replaced with BitAPAI

**Comment by crazydevlegend** [comment]
And can you share your `.env` file?

**Comment by sabinbaniya** [comment]
> image I still see openai, chatgpt here... Please check all pages and confirm all are replaced with BitAPAI

Okay

**Comment by sabinbaniya** [comment]
> And can you share your `.env` file?

Here:

.env.local.example
```
# Chatbot UI
DEFAULT_MODEL=gpt-3.5-turbo
OPENAI_API_KEY=YOUR_KEY

# Google
GOOGLE_API_KEY=YOUR_API_KEY
GOOGLE_CSE_ID=YOUR_ENGINE_ID
```

**Comment by crazydevlegend** [comment]
> > And can you share your `.env` file?
> 
> Here:
> 
> .env.local.example
> 
> ```
> # Chatbot UI
> DEFAULT_MODEL=gpt-3.5-turbo
> OPENAI_API_KEY=YOUR_KEY
> 
> # Google
> GOOGLE_API_KEY=YOUR_API_KEY
> GOOGLE_CSE_ID=YOUR_ENGINE_ID
> ```

Still OPENAI_API_KEY? ....
should REPLACE WITH BitAPAI_API_KEY.

and we don't need DEFAULT_MODEL...

**Comment by sabinbaniya** [comment]
Screenshot 2023-06-28 091442

**Comment by crazydevlegend** [comment]
@sabinbaniya let me merge and run on my local

**Comment by crazydevlegend** [comment]
@sabinbaniya 
image
I noticed, right panel doesn't work - in original repo, it works.
Please make it work (maybe your changes broke the code? or sth? I'm not sure)

After fixing this make another PR.

**Comment by sabinbaniya** [comment]
> @sabinbaniya image I noticed, right panel doesn't work - in original repo, it works. Please make it work (maybe your changes broke the code? or sth? I'm not sure)
> 
> After fixing this make another PR.

Sure lemme check

**Comment by sabinbaniya** [comment]
> @sabinbaniya image I noticed, right panel doesn't work - in original repo, it works. Please make it work (maybe your changes broke the code? or sth? I'm not sure)
> 
> After fixing this make another PR.

Did you mean creating, updating and deleting the prompts?
Its working in mine

image

Screenshot 2023-06-29 065201

image

image

**Comment by crazydevlegend** [comment]
yes, that feature... let me check again on my end @sabinbaniya

**Comment by crazydevlegend** [comment]
@sabinbaniya it doesn't work.

**Pull request merged**
