### PR TITLE
docs: add integration documentation

### PR DESCRIPTION
**Pull request by sabinbaniya**

### CODE REVIEW

**Review by crazydevlegend — CHANGES_REQUESTED** [review]
bitapai -> BitAPAI
it's brand name, so make sure you use them in the right format.

**Comment by sabinbaniya** [comment]
> bitapai -> BitAPAI it's brand name, so make sure you use them in the right format.

Oh okay

**Comment by sabinbaniya** [comment]
> bitapai -> BitAPAI it's brand name, so make sure you use them in the right format.

@crazydevlegend , done.

**Review by crazydevlegend — CHANGES_REQUESTED** [review]
remove commit hashes, instead, just use bullets

**Review by crazydevlegend — APPROVED** [review]

**Pull request merged**
