### PR TITLE
fix: fix right sidebar create prompt, load apikey from env if available

### PR DESCRIPTION
**Pull request by sabinbaniya**

### CODE REVIEW

**Comment by sabinbaniya** [comment]
@crazydevlegend I have fixed the two issues can you have a look?
Note: the env file for loading API key should be changed from `.env.local.example` to `.env.local`

**Comment by crazydevlegend** [comment]
@sabinbaniya it works - awesome

**Comment by crazydevlegend** [comment]
image
btw, can you plz write how to use variables in the prompt?

**Comment by sabinbaniya** [comment]
> 

In the documentation?

**Pull request merged**
